name = "SparseGridQuadrature"
uuid = "783fc400-e4cb-4fe0-842f-3d091e33b2c9"
authors = ["Erik Schnetter <schnetter@gmail.com>"]
version = "1.0.0"

[deps]
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DoubleFloats = "1.1"
Setfield = "1.0.0"
StaticArrays = "1.4.4"
julia = "1.0"

[extras]
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DoubleFloats", "Random", "Test"]
